### ISSUE TITLE
Execution of tests is failing

### ISSUE THREAD

**Issue by 77** [JohnnyHendriks/TestAdapter_Catch2#12]
I'm seeing this error. Test discovery is working fine. Any ideas? 

An exception occurred while invoking executor 'executor://catch2testexecutor/': The directory name is invalid

**Comment by JohnnyHendriks** [comment]
The only thing I can think of at the moment is that the working directory for the tests is set to a non-existing directory. This particular issue should be fixed with the next release. If you need the fix now you can [build the current version of the adapter yourself](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/master/Docs/Build.md). Version number of the current main branch has been increased (currently to 1.4.1) to make sure installing the self build version updates the one obtained via Visual Studio Marketplace.

**Comment by 77** [comment]
I'll give it a shot. Thanks.
