### ISSUE TITLE
All failed test display: Message: Invalid test runner output.

### ISSUE THREAD

**Issue by tishion** [JohnnyHendriks/TestAdapter_Catch2#23]
![image](https://user-images.githubusercontent.com/5869938/54916498-9e0c2300-4f34-11e9-9c40-f6789c69e81d.png)

Catch2 version v2.7.0.
Visual studio 2017 

1.Just wondering is this project still being maintained?
2.Are you going to fix this issue?

**Comment by JohnnyHendriks** [comment]
Yes, this project is still being maintained. However, I don't think I can help much with fixing this issue. The problem seems to be that the test executable crashed before it could finish writing the xml output. As a result the test adapter received an incomplete output, which it cannot parse. In order for you to be able to diagnose the problem the partial output is provided to you unprocessed.

The best course of action I can recommend is to run the test in Debug mode and step through the location around the last test failure. That may give you a hint for why the test executable unexpectedly crashed. Another thing you may try is to run the test executable from the command prompt. It might give a little additional information. Note that the test adapter only runs one test case at a time (_i.e._, a separate process for each test case). It is possible that tests pass just fine when executed from the same process, but fail in isolation (the reverse can also happen).

As this seems to be a problem with the test executable and not the test adapter, it falls out of the scope of things I can fix on the test adapter side. As such I will close this issue. Feel free to re-open it if you think it really is a test adapter problem.

**Comment by tishion** [comment]
Thanks. Now i know the exact cause of this problem. because we disabled C++ exception in all binary output including the unit tests, when the assertion failed the test runner will be terminated. It seems i need to enable the C++ exception. 

Thank you.

**Comment by LordOfTheCows** [comment]
> Yes, this project is still being maintained. However, I don't think I can help much with fixing this issue. **The problem seems to be that the test executable crashed before it could finish writing the xml output**. 

I had the exact same problem, and it was indeed an error occurring after the catch exception was thrown that prevented the program from terminating correctly. It's an easy problem to miss (a thread was not terminating correctly). Perhaps a note in the documentation could help others like me :)
