### ISSUE TITLE
Can't intall testadapter catch2 because of prerequisites issue

### ISSUE THREAD

**Issue by DamDre** [JohnnyHendriks/TestAdapter_Catch2#25]
Hi All,
I downloaded catch2 from https://marketplace.visualstudio.com/items?itemName=JohnnyHendriks.ext01  but when I try to install it for vs2017 Pro, I have an error like "The extension cannot be installed to this product due to prerequisites that cannot be resolved" .
Do you know why please ?
We have Visual studio professional 2017 15.4 and it seems that catch2 is for vs2017 and vs2019. 
Thanks in advance.

**Comment by JohnnyHendriks** [comment]
Yes, the test adapter should work both on VS2017 and VS2019. I actually work with it myself on both VS2017 and VS2019 on a daily basis (both the professional and Community version). When creating an extension a prerequisite must be provided. I chose for "Visual Studio C++ core features" as a prerequisite. As such the Core C++ feature must be installed before you can install the **Test Adapter for Catch2**. This seems reasonable as the test adapter is for a C++ unit test framework. 

I hope this helps.

**Comment by DamDre** [comment]
Hi @JohnnyHendriks ,
Thanks for your answer, it works for vs2017 15.9 but not for vs2017 15.4 even if I'm sure that I choose "visual studio c++ core features" during installation.
Do you know something about this?

**Comment by JohnnyHendriks** [comment]
Sadly I'm not able to test on VS2017 15.4. It is possible that the c++ core features requirement option was added after 15.4. I had some trouble with moving to VS2019 where there were some changes in possible prerequisites. In that case the only option would be to build the test adapter yourself on VS2017 15.4 and change the prerequisites in the VSIX/VSTestAdapterCatch2 project to something that works (double click source.extension.vsixmanifest to open the manifest file gui).

Note, if the only reason you need to use VS2017 15.4 is because of the C++ toolset you use, it is possible to use side by side toolsets. Myself I make use of toolset 14.12 and 14.16 side by side at work. If you make use of CMake it has an option to select a specific toolset (I think this is possible since CMake 3.13). You can even use the 14.12 toolset in VS2019, even though it is not part of the installer by copying the 14.12 toolset folder from the VS2017 installation to the appropriate place in the VS2019 installation.

**Comment by DamDre** [comment]
Thanks a lot. I think we can close the issue
