### ISSUE TITLE
Test case names

### ISSUE THREAD

**Issue by matt77hias** [JohnnyHendriks/TestAdapter_Catch2#30]
It seems that having `[` , `]` and `,` in test case names does not work anymore. Tests are still detected, but could not be executed in Visual Studio 2019. 

Furthermore, `::` causes some subgrouping, which is very unfortunate if you want to use for example, `std::string` somewhere in the middle of the test case name. It is sort of ok-ish if it belongs to the prefix. (`:` works fine)

**Comment by JohnnyHendriks** [comment]
Sorry for the late response. I did a quick check and this problem seems to be introduced with Catch v2.9.2. Previous versions do not seem to have this problem. So I assume you were using v2.9.2 of Catch2.

With regard to subgrouping. This is a Test Explorer thing. It has always been there, but with VS2019 you have a little more control on how it displays this info. If you go to the group by button in the Test Explorer and you select to group only by "Project" the subgrouping is turned off. I put some info on this in the [documention on capabilities](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/master/Docs/Capabilities.md#notes-on-test-case-names)

**Comment by JohnnyHendriks** [comment]
I created an [issue](https://github.com/catchorg/Catch2/issues/1737) with Catch2 for this.

**Comment by matt77hias** [comment]
Yes, I am using Catch2 v2.9.2.

Thanks for looking into this and forwarding it to Catch2. 👍

**Comment by ThrashAbaddon** [comment]
Issue is resolved on Catch2 side.
