### ISSUE TITLE
Libraries using `printf` reported as test failure. Maybe that could be improved?

### ISSUE THREAD

**Issue by LYP951018** [JohnnyHendriks/TestAdapter_Catch2#34]
e.g., what if we add 

```cs
int start = _xmloutput.IndexOf(@"<Catch ")
```

to `ProcessXml`?

I could submit a PR for this.

**Comment by JohnnyHendriks** [comment]
Thank you for your suggestion. However, the problem with `printf` is that its output is not captured by the Catch2 framework. As such output generated by `printf` can appear (semi) randomly in the Catch2 xml reporter output, resulting in invalid XML that cannot be read by an Xml parser.

But as I'm writing this answer I came up with a possible solution. I've been making some changes recently that also effect Xml report handling for an upcoming feature. Based on those changes I now do have an idea to maybe fix this. Basically, instead of reporting to the default output, send the report to a file. Maybe the `printf` output will then not be intertwined with the Xml report. I will have a look if this helps solve this problem.

**Comment by JohnnyHendriks** [comment]
Update. I was able to test the possible solution today and it seems to work. As such it will be part of the next release.

**Comment by JohnnyHendriks** [comment]
Finally released the new version (1.6.0) that fixes this problem. So closing this issue.
