### ISSUE TITLE
Test runtimes are reported incorrectly

### ISSUE THREAD

**Issue by fschoenm** [JohnnyHendriks/TestAdapter_Catch2#7]
It seems as if the test run times in the test explorer are reported incorrectly. My whole test run just took a few seconds but every test is reported to have run minutes to days:

![catchtestadapter-long-runtimes](https://user-images.githubusercontent.com/687230/45150318-d718bc00-b1cb-11e8-8f34-132a72e54fc1.png)

Here's a log file of the above run: [catchtestadapter-long-runtimes.txt](https://github.com/JohnnyHendriks/TestAdapter_Catch2/files/2356492/catchtestadapter-long-runtimes.txt)

Maybe it's a problem with parsing the duration in the test output (e.g. because of locale settings). If you interpret e.g. `durationInSeconds="0.184119"` as 184119 seconds, you would get the 3068 minutes in the above screenshot.

**Comment by JohnnyHendriks** [comment]
Thank you for reporting this. A classic case of parsing double values with a decimal separator that is a point in a globalization setting where it is set to something else.

The Catch2 xml output used by the **Test Adapter for Catch2** is generated without taking into account the globalization setting of the system. Processing the floating point duration value in the xml output was taking globalization settings into account. This has now been fixed so that the floating point duration value is always parsed expecting a decimal point as a decimal symbol irrespective of the globalization setting of the system. The fix will be part of the next release.
