### ISSUE TITLE
[Bug] When running in VStest (Dev-Ops) and an exception in "testRunStarting" then tests runs are stuck in a loop

### ISSUE THREAD

**Issue by Smurf-IV** [JohnnyHendriks/TestAdapter_Catch2#70]
Using 
- Catch2 V 3.4
- VS 17.7.x
- override event `testRunStarting` and register via `CATCH_REGISTER_LISTENER`
  - this throws an exception which is caught by the Catch2 main runner catch block

2 Problems:
1) Within visual studio the event exception just stops the runner, and nothing is displayed in the tree output (Other frameworks display a message if a Setup style exceptions occur)

2) when run in vstest (console and in Dev-ops pipeline) the test just gets stuck in a loop:
(There is only a single test in the exe to demonstrate)
![image](https://github.com/JohnnyHendriks/TestAdapter_Catch2/assets/2418812/b83a5b01-0da2-4e56-918a-8fd54b6f400d)

**Comment by Smurf-IV** [comment]
VStest yml command:
![image](https://github.com/JohnnyHendriks/TestAdapter_Catch2/assets/2418812/fee1bbb7-bddc-4c86-b125-bb60d6a426f1)

**Comment by Smurf-IV** [comment]
RunSettings:
![image](https://github.com/JohnnyHendriks/TestAdapter_Catch2/assets/2418812/e02b56db-1269-44af-9dea-ed121260a329)

**Comment by JohnnyHendriks** [comment]
Sorry for the late response. I guess the exception causes the start of the test to not be logged in the result report. As such it is marked as not run yet, and the test is retried. If you didn't set a timeout, this will cause an endless loop. This is now fixed in the latest release (v2.0.0 of the Test Adapter for Catch2). It will now detect that the same number of tests need to be re-run and in that case will not try to re-run the not yet run tests.
